#!/usr/bin/env python3
"""Freehold — write the golden corpus out as real .xlsx files.

    python3 ops/make-test-sheets.py

The same five grids the test suite asserts (app/tests/samples.py) become five
files under docs/testing/sheets/, so the identical contract can be checked by
hand in a browser on sandbox. One source, two audiences: pytest and Angel.

They are deliberately tiny and boring. Each one provokes exactly ONE behaviour,
so when a run comes back wrong you know which brake failed instead of squinting
at 45 rows of real data. And unlike the real call list, these contain no
customer data at all — so they are safe to commit to a public repo, which is
the whole reason they exist.
"""
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "app"))

from tests import samples as S            # noqa: E402
from tests._xlsx import make_xlsx         # noqa: E402

OUT = REPO / "docs" / "testing" / "sheets"

WHAT = {
    "1-clean-contacts": (
        "The control. Nothing is wrong with it.",
        ["4 rows, 5 columns, every cell filled",
         "Quality score 1.00 on every row — nothing missing",
         "All 4 phones already E.164, so the rule resolves all 4 and declines none",
         "No reconcile offered (only one phone column) and no duplicates",
         "THE POINT: a tool that finds ten things to fix on clean data is a tool "
         "nobody trusts. If this sheet produces a long menu, that is the bug."],
    ),
    "2-messy-phones": (
        "The rules' exam paper — two columns claiming the same fact.",
        ["7 rows. The rule resolves 4 and declines 3, and the 3 are the right 3",
         "Eursap NL      -> agree      (+31 20 890 8064 == +31 (0) 20 890 8064)",
         "Hays CH        -> only_phone (right side has an email, no number)",
         "Westhouse      -> conflict   (a German office and a Swiss one)",
         "Montash        -> conflict   (same number with an extension glued on)",
         "Michael Bailey -> only_phone (left cell holds TWO numbers -> declined)",
         "Local NL       -> no finding ('020 36 30 310' declines: leading 0, "
         "unknown country. Guessing +1 here would be a US number — the bug we hit "
         "on the real call list)",
         "Freelancermap  -> no finding (a URL is not a phone number)"],
    ),
    "3-notes-in-the-data": (
        "The row that isn't a record. Every real spreadsheet grows this tail.",
        ["8 rows survive the reader (the blank spacer row is dropped, the notes are not)",
         "3 are real records, scoring 1.00",
         "5 are your own notes — PROGRESS, Calls made, BEST TIME TO CALL … — "
         "sitting in the same columns, scoring 0.25",
         "THE POINT: the junk separates itself by completeness alone, with no AI "
         "involved. This is what happened by accident on your real call list."],
    ),
    "4-dirty-headers": (
        "The reader's exam paper. Headers as people actually type them.",
        ["Two columns both called PHONE, plus a lowercase 'phone' -> kept as "
         "phone, phone_2, phone_3. None is silently dropped",
         "A blank header becomes 'col'",
         "'Full Name!' -> full_name, 'Ort / City' -> ort_city",
         "2 data rows",
         "THE POINT: two columns claiming one fact is a FINDING, not a nuisance."],
    ),
    "5-several-tabs": (
        "Three tabs of different shapes. Freehold reads ONE.",
        ["The tab picker shows: Call List, Catalogue, Invoices",
         "Choosing tab 1 reads agency/phone; tab 2 reads product/price/category; "
         "tab 3 reads invoice/amount/due",
         "THE POINT: silently importing the WRONG tab is the worst bug of all, "
         "because the output looks perfectly fine."],
    ),
}


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    lines = ["# Test sheets — the golden corpus", "",
             "Generated by `python3 ops/make-test-sheets.py`. **Do not hand-edit** —",
             "edit `app/tests/samples.py` and regenerate, so the files and the test",
             "suite can never drift apart.", "",
             "Every expected answer below is asserted by `app/tests/test_samples.py`.",
             "Upload each file at `/lists` (brain: *Rules only* is enough for all of",
             "them) and check what you see against this list.", ""]

    for name, (grid, tabs) in S.SAMPLES.items():
        blob = make_xlsx(grid, tabs)
        path = OUT / f"{name}.xlsx"
        path.write_bytes(blob)
        title, expects = WHAT[name]
        print(f"  {path.relative_to(REPO)}  ({len(blob):,} bytes)")
        lines += [f"## {name}.xlsx", "", f"*{title}*", "", "Expect:", ""]
        lines += [f"- {e}" for e in expects] + [""]

    (OUT / "README.md").write_text("\n".join(lines))
    print(f"  {(OUT / 'README.md').relative_to(REPO)}")
    print(f"\n✅ {len(S.SAMPLES)} sheets + README in {OUT.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
