POSTGRES_USER: ENC[AES256_GCM,data:Edt8EZwkcC8=,iv:9setOoY9301WkDjO+ehHnTQ/u/pPh3kVJBnm/fDdFgY=,tag:55Nc2kk7zvMWUa2qzIVYPQ==,type:str]
POSTGRES_PASSWORD: ENC[AES256_GCM,data:BGfGPw927l8GoBRaQkjY8j8tANHI,iv:V0g3xKwVe94ta7F0Cs7mz2/5vrGh/XplmD6cHg+E8MI=,tag:8PWGsWITp76/18SYOb0gcw==,type:str]
POSTGRES_APP_DB: ENC[AES256_GCM,data:MeoXDV+eqk4=,iv:qrauhVCGGA1bqMJUNWB2coyLHgUre4yIwVZZP0VrUus=,tag:aIPxzogfBfX1qNogn2bsFQ==,type:str]
POSTGRES_KC_DB: ENC[AES256_GCM,data:qlk7O1d/TRQ=,iv:wc+/qsb80k5x83wxp5zBOufH0VdPV9EARNrb5gviiM4=,tag:T/sFyx15i78vQo4TME8tdg==,type:str]
KC_BOOTSTRAP_ADMIN_USERNAME: ENC[AES256_GCM,data:ZAfcDR0=,iv:18lzLYq79jKwSEjDae5mZY8OINLmlWyA6rafgQObxYY=,tag:ku2ed4BWP8ZWJhMmkNvNxw==,type:str]
KC_BOOTSTRAP_ADMIN_PASSWORD: ENC[AES256_GCM,data:4twk1YdzMks6+96gmyqekpjc3DU0,iv:n//z8LP9y3VtLziYuj/Oz/P1HCpdM8UYZfAd+RnVMjA=,tag:8Rw67uTBgLfb5ylyhe4Hzw==,type:str]
APP_ENV: ENC[AES256_GCM,data:LRdsXJ8p9p071A==,iv:lyfVKjggMEam4yf4hCApCVZLYtLVuAwSINu5ezlbedw=,tag:X+lJFF6ksE0ut51YTlkILA==,type:str]
KC_REALM: ENC[AES256_GCM,data:OH3ImlJR,iv:TE1SZ9WpRMEwZgYLBizlOrePT8Lw5H+20UOvtVOxkyo=,tag:ZXQYRAxmhEpbrG3XdDKIyQ==,type:str]
SITE_DOMAIN: ENC[AES256_GCM,data:U6XuDFs5F325DIA4UUhelQ==,iv:bcLuxxq3chO8wxh6IOJFa8bJyJlXljR5uoMUc3vXiBo=,tag:glz0XDZj8L36weGUqVWBdw==,type:str]
APP_BASE_URL: ENC[AES256_GCM,data:/s1wncoAcH9FVGvncAcGooT1wbcTOsI3,iv:pZNVIIvgCd3oM5rsZzT+8St+hT7lPrU9n33rlaiBbiI=,tag:/1T8GQZrZ0QdreQKHhepHQ==,type:str]
APEX_DOMAIN: ENC[AES256_GCM,data:05YTqe2ssg2jarVCPaVSDwBcyW8VZSs3nHJGrji0qVID3mzSVgxm2bI8whASAge7x7NFsxTwinXUE1y+TPWVug==,iv:8ue6kpiT3sMCza0TrkVWgBoHI7yKpIXRm2hMIXaqKHM=,tag:bu5uSHIPm+/aJPxjfQr9TA==,type:str]
AUTH_DOMAIN: ENC[AES256_GCM,data:G9TDoPAoTdisHcSoJaeaTQo=,iv:JPccQjRljfX7bdyQ+kazhGzQ/znO92i5wJj3bzAUWjU=,tag:NUjPQMI+m5kFBSizYhpPvg==,type:str]
KC_PUBLIC_URL: ENC[AES256_GCM,data:ZaPgM+RwcFXIzrZZ+YMSJZqJ7rn7WdtEwQ==,iv:e3USNWq/8Z5SZqYNcNPXaOq49RZKzNTc+g1M5fWPCDM=,tag:tIb9MfGFOHfS+tb3fDBgJg==,type:str]
KC_INTERNAL_URL: ENC[AES256_GCM,data:5PvQzQDFxfqnvEwoCEGVvVTYoMg=,iv:2LyvmSkv3Nk/iaKbvRm3zS2W6p/RzcEXwMN6BcDv6cc=,tag:5OyXxUTuncvrbD5DLDb+OA==,type:str]
KC_CLIENT_ID: ENC[AES256_GCM,data:bu/k9TWE01qaq0i7,iv:Kbc58Afl7dnNRVT+4Ss8l4EUyQfPi6U5WGWR3TsjPPc=,tag:vbrNU6wPZiFWoFySBA8rKg==,type:str]
KC_CLIENT_SECRET: ENC[AES256_GCM,data:eP6XWasI8MFEW9tuhvP8jZf1JSeP9JPBpPUEfw==,iv:zhF10yCE9+QUDK1auP1eICBmmD53XBBKw7yHJ3ACfj4=,tag:sgbuc9QIgq89NSGQOXrKCg==,type:str]
SESSION_SECRET: ENC[AES256_GCM,data:Li/L/PW23ROAEfy7JX6XNOIALgsPSRC89MZ6lknuKo1R,iv:s8TQvQD+mndRoEEvSFk0Egl9I5me8ATPW1sa63pWp1o=,tag:TWbjvvbQqXK07GpN2Ln8aQ==,type:str]
SESSION_COOKIE_SECURE: ENC[AES256_GCM,data:6gsW4w==,iv:2n9JzH4e/IGL0kfNNhmQKW89UvJm0DELzYBGY8Rp+Ys=,tag:twy2I9bblKs67Cy2I9he5Q==,type:str]
BACKUP_PASSPHRASE: ENC[AES256_GCM,data:MxkPgCdpaTDnm+DRtuanHV5LQaigo+lXNzS8gjy641s=,iv:LK0Deh2jKHVmfEZmAIDnFiEa7Z1TPy5M3kV1LDDnwWI=,tag:4jUvEzAZL8PllWFXNO7j1A==,type:str]
RESEND_API_KEY: ENC[AES256_GCM,data:q0fYz4i4OhqM1nYdvhsx8jhGzb9UFBkd,iv:OEY+8+CQUcJZvIZnqNWrfCSpof9jZjc8ugNZ8Ms+6ug=,tag:c0cqEvtZPjNNLLeNZeXWvw==,type:str]
GOOGLE_CLIENT_ID: ""
GOOGLE_CLIENT_SECRET: ""
GITHUB_CLIENT_ID: ""
GITHUB_CLIENT_SECRET: ""
FACEBOOK_CLIENT_ID: ""
FACEBOOK_CLIENT_SECRET: ""
MINIO_ROOT_USER: ENC[AES256_GCM,data:5j4ukUsE2QQ=,iv:a/DUiOZ+nU+5g+tgk4O8bVow/Fowqd5bybg1fy5Teac=,tag:Yh9h708MsR0Kykj3UsFTGQ==,type:str]
MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:KvnXy8UedtoxxycvkXsXdhdJ6P0=,iv:NFMnF4UgiZcWz1Dpl/zVIAzkQ4r7GbkpY9fJEneHLRw=,tag:Sgk3shNr5JcW4SlfyhjiHg==,type:str]
MINIO_ENDPOINT: ENC[AES256_GCM,data:6Z7Qv+C+7zuv7Q==,iv:Zu5KH3KoUGfOrDo2PCNKx3xQ1SmQVwcKMysRqlT72y8=,tag:uRV4rI/NcCr4+OPvdXYYxQ==,type:str]
MINIO_BUCKET: ENC[AES256_GCM,data:cX5UDcfCemk=,iv:OBLw8+6lhaabOPqWiAjYyZGQxgyXfE4qah8xaJhzeQA=,tag:Sc9CdVS+c6aWZse5rEli6A==,type:str]
ROBOT_URL: ENC[AES256_GCM,data:iMWFdZOh1iEdiGuxPYzYSsygt5f+,iv:t7EcJx2kjkZn+sjiYtXLeW0RZProPa//5lvNyhvT5Lc=,tag:DfSaIsMq0A7ftm7hDrtKUw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hhge8meh9m87ztcntld32zdet0q8cfkx2yezt66j8zzwppu7wezshzpazq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyR0k2L0t6OElRUnZFNzAv
            dWRmNHJwcTk3U0NBVGxQNU5NWC84anpMUXdRCkJtaTdpSjVxZU44anJ4aXJFblBV
            NGRUSDlETVJmaWcrS1NUMS9kSGo4OFEKLS0tIHA5bkNMT0g0VVZzRGRBVlVRWlNi
            WWdqZklwSUpDMnpwL0ROQ0hvZCtGQk0KGAbZsjbZ713pZqxZoIbSLyExyBQZaSLe
            JdYOMc3SCdvxu3Tk2AYNuV9kXpSptJih93a5JzRDeFMnCOrhHopkNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-04T10:01:28Z"
    mac: ENC[AES256_GCM,data:noOcYmiRszOhM/eOVcHBPAEDVsxbFL5KV10N8mjBdfbIqgc/BCKpDKuMNh6GGg7UVhYyWVpHgQYnLzbJ5oQ4pFTHMo45z6YgfyHvwv6jmakCWYxinGXkaJr+VkO3ciiBgiy2WtC3ZZbTanpGd8xzKNrukw4w7kWOw7fEqTK0sOs=,iv:7IhMxz2j7Z+CgZ+828F0LlM6WMPIKUch9CsK/KY64gE=,tag:Ir5Xlq82bTsGzp1aWkT44g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
